-- Migration 0007 — Import 2 : ajout de 18 appartements (append, aucun wipe)
-- Aucune collision de slug avec les 28 existants. sort_order 28..45.
-- LX A7F : is_published=false (loyer + surface manquants dans le sheet).

insert into properties (
  slug, ref, dispo, arrondissement, quartier, name, name_italic,
  baseline, short_description, long_description, surface, chambres, sdb,
  etage, couchages, min_stay, loyer_num, inclus, is_published, sort_order
) values
  ('appt-beaumarchais-11-beaumar-5r','11 BEAUMAR 5R','Disponible','11ᵉ Arrondissement','Bastille','Appt','Beaumarchais','T2 haussmannien de 36 m2 tout équipé.','36 m2 · 1 chambres · 1 salles de bain · 5 étage avec ascenseur.','{}','36 m²','1','1','5','','30 nights',2500,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,28),
  ('appt-beaumarchais-11-beaumar-2l','11 BEAUMAR 2L','Disponible','11ᵉ Arrondissement','Bastille','Appt','Beaumarchais','T3 haussmannien de 66 m2 tout équipé.','66 m2 · 2 chambres · 2 salles de bain · 2 étage avec ascenseur.','{}','66 m²','2','2','2','','30 nights',6100,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,29),
  ('appt-la-pompe-lx-b6l','LX B6L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T5 haussmannien de 108 tout équipé.','108 · 4 chambres · 2 salles de bain · 6 étage avec ascenseur.','{}','108 m²','4','2','6','10','30 nights',7500,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,30),
  ('appt-la-pompe-lx-b7l','LX B7L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T6 haussmannien de 175 tout équipé.','175 · 5 chambres · 5 salles de bain · 7 étage avec ascenseur.','{}','175 m²','5','5','7','10','30 nights',12100,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,31),
  ('appt-la-pompe-lx-a3l','LX A3L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T4 haussmannien de 127 tout équipé.','127 · 3 chambres · 2 salles de bain · 3 étage avec ascenseur.','{}','127 m²','3','2','3','5','30 nights',8800,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,32),
  ('appt-la-pompe-lx-a1r','LX A1R','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T3 haussmannien de 85 tout équipé.','85 · 2 chambres · 1 salles de bain · 1 étage avec ascenseur.','{}','85 m²','2','1','1','6','30 nights',5900,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,33),
  ('appt-la-pompe-lx-a2r','LX A2R','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T3 haussmannien de 85 tout équipé.','85 · 2 chambres · 1 salles de bain · 2 étage avec ascenseur.','{}','85 m²','2','1','2','6','30 nights',5900,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,34),
  ('appt-la-pompe-lx-p4r','LX P4R','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T4 haussmannien de 150 tout équipé.','150 · 3 chambres · 2 salles de bain · 4 étage avec ascenseur.','{}','150 m²','3','2','4','6','30 nights',10500,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,35),
  ('appt-la-pompe-lx-ardc','LX ARDC','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T2 haussmannien de 62 tout équipé.','62 · 1 chambres · 1 salles de bain · RDC étage avec ascenseur.','{}','62 m²','1','1','','4','30 nights',3600,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,36),
  ('appt-la-pompe-lx-b2l','LX B2L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T3 haussmannien de 109 tout équipé.','109 · 2 chambres · 2 salles de bain · 2 étage avec ascenseur.','{}','109 m²','2','2','2','8','30 nights',7600,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,37),
  ('appt-la-pompe-lx-rdc','LX RDC','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T2 haussmannien de 69 tout équipé.','69 · 1 chambres · 2 salles de bain · RDC étage avec ascenseur.','{}','69 m²','1','2','','6','30 nights',4000,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,38),
  ('appt-la-pompe-lx-b3rr','LX B3RR','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T2 haussmannien de 70 tout équipé.','70 · 1 chambres · 1 salles de bain · 3 étage avec ascenseur.','{}','70 m²','1','1','3','4','30 nights',4100,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,39),
  ('appt-la-pompe-lx-b4rf','LX B4RF','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T2 haussmannien de 70 tout équipé.','70 · 1 chambres · 1 salles de bain · 4 étage avec ascenseur.','{}','70 m²','1','1','4','6','30 nights',4100,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,40),
  ('appt-la-pompe-lx-a1l','LX A1L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T3 haussmannien de 120 tout équipé.','120 · 2 chambres · 2 salles de bain · 1 étage avec ascenseur.','{}','120 m²','2','2','1','8','30 nights',8300,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,41),
  ('appt-la-pompe-lx-p4l','LX P4L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T5 haussmannien de 280 tout équipé.','280 · 4 chambres · 3 salles de bain · 4 étage avec ascenseur.','{}','280 m²','4','3','4','8','30 nights',18000,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,42),
  ('appt-la-pompe-lx-p5l','LX P5L','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T5 haussmannien de 280 tout équipé.','280 · 4 chambres · 4 salles de bain · 5 étage avec ascenseur.','{}','280 m²','4','4','5','8','30 nights',18000,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,43),
  ('appt-la-pompe-lx-a7r','LX A7R','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T2 haussmannien de 70 tout équipé.','70 · 1 chambres · 2 salles de bain · 7 étage avec ascenseur.','{}','70 m²','1','2','7','6','30 nights',4900,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],true,44),
  ('appt-la-pompe-lx-a7f','LX A7F','Disponible','16ᵉ Arrondissement','Foch','Appt','La Pompe','T1 haussmannien de  tout équipé.',' ·  chambres ·  salles de bain · 7 étage avec ascenseur.','{}','','','','7','','30 nights',0,ARRAY['Ménage hebdomadaire','Wi-Fi','Charges & taxe de séjour incluses','Cuisine équipée','Conciergerie','Linge']::text[],false,45)
on conflict (slug) do nothing;
